Repository peek-travel/swift-currency, pull requests merged in 2025-01, with the labels that each got.

#40 Re-implement the basic concept of 'Currency' with Decimal storage
  .editorconfig
  Package.swift
  Sources/Currency/Currency+Algorithms.swift
  Sources/Currency/Currency+Arithmetic.swift
  Sources/Currency/Currency+StringRepresentation.swift
  Sources/Currency/Currency.swift
  Sources/Currency/CurrencyDescriptor.swift
  Sources/Currency/Extensions/Sequence+Currency.swift
  Sources/Currency/MinorUnitRepresentation.swift
  Sources/ISOStandardCodegen/ISOCurrencyGeneration.swift
  Tests/CurrencyTests/Currency+AlgorithmsTests.swift
  Tests/CurrencyTests/Currency+ArithmeticTests.swift
  Tests/CurrencyTests/Currency+StringRepresentationTests.swift
  Tests/CurrencyTests/CurrencyDescriptorTests.swift
  Tests/CurrencyTests/CurrencyTests.swift
  Tests/CurrencyTests/Sequence+CurrencyTests.swift
Labels: bug, enhancement, semver-major

#41 Re-write CurrencyMint implementation for new Currency protocol
  Sources/Currency/CurrencyMint.swift
  Sources/ISOStandardCodegen/MintISOSupportGeneration.swift
  Tests/CurrencyTests/CurrencyMintTests.swift
Labels: enhancement, semver-major

#42 Replace AnyCurrency, CurrencyProtocol with new Currency implementation
  Sources/Currency/AnyCurrency+Algorithms.swift
  Sources/Currency/AnyCurrency+Sequence.swift
  Sources/Currency/AnyCurrency.swift
  Sources/Currency/CurrencyProtocol.swift
  Sources/Currency/Extensions/Decimal.swift
  Sources/ISOStandardCodegen/ISOCurrencyGeneration.swift
  Sources/ISOStandardCodegen/MintISOSupportGeneration.swift
  Tests/CurrencyTests/AnyCurrencyAlgorithmsTests.swift
  Tests/CurrencyTests/AnyCurrencyTests.swift
  Tests/CurrencyTests/Currency+AlgorithmsTests.swift
  Tests/CurrencyTests/Currency+ArithmeticTests.swift
  Tests/CurrencyTests/Currency+StringRepresentationTests.swift
  Tests/CurrencyTests/CurrencyDescriptorTests.swift
  Tests/CurrencyTests/CurrencyMintTests.swift
  Tests/CurrencyTests/CurrencyTests.swift
  Tests/CurrencyTests/Sequence+CurrencyTests.swift
Labels: enhancement, semver-major

#43 Replace CSV with JSON as file format for ISO Currency definitions
  ISO4217.csv
  ISO4217.json
  Package.swift
  Plugins/ISOStandardCodegenPlugin/plugin.swift
  Sources/ISOStandardCodegen/CSVParsing.swift
  Sources/ISOStandardCodegen/Codegen+CurrencyDefinitions.swift
  Sources/ISOStandardCodegen/Codegen+DefinitionParsing.swift
  Sources/ISOStandardCodegen/Codegen+FileHeader.swift
  Sources/ISOStandardCodegen/Codegen+MintLookup.swift
  Sources/ISOStandardCodegen/ProcessingError.swift
  Sources/ISOStandardCodegen/main.swift
Labels: enhancement, semver-patch

#44 Update CI test file to handle latest supported versions of Swift
  .github/workflows/codecov.yml
  .github/workflows/tests.yml
Labels: enhancement

#45 Rename Currency protocol to CurrencyValue
  Sources/Currency/CurrencyMint.swift
  Sources/Currency/CurrencyValue+Algorithms.swift
  Sources/Currency/CurrencyValue+Arithmetic.swift
  Sources/Currency/CurrencyValue+StringRepresentation.swift
  Sources/Currency/CurrencyValue.swift
  Sources/Currency/Extensions/Sequence+Currency.swift
  Sources/ISOStandardCodegen/Codegen+CurrencyDefinitions.swift
  Sources/ISOStandardCodegen/Codegen+MintLookup.swift
  Tests/CurrencyTests/CurrencyMintTests.swift
  Tests/CurrencyTests/CurrencyValue+AlgorithmsTests.swift
  Tests/CurrencyTests/CurrencyValue+ArithmeticTests.swift
  Tests/CurrencyTests/CurrencyValue+StringRepresentationTests.swift
  Tests/CurrencyTests/CurrencyValueTests.swift
Labels: bug, semver-major

#46 Simplify the CurrencyValue protocol
  Sources/Currency/CurrencyValue+Arithmetic.swift
  Sources/Currency/CurrencyValue+StringRepresentation.swift
  Sources/Currency/CurrencyValue.swift
Labels: enhancement, semver-major

#47 Enforce CurrencyDescriptor equality for comparable with compiler
  Sources/Currency/CurrencyValue.swift
  Tests/CurrencyTests/CurrencyValueTests.swift
Labels: bug, semver-major

#48 Provide instance level access to descriptor information
  Sources/Currency/CurrencyValue.swift
  Tests/CurrencyTests/CurrencyValueTests.swift
Labels: enhancement, semver-minor

#49 Update project documentation for new state of the world
  README.md
  Sources/Currency/CurrencyDescriptor.swift
  Sources/Currency/CurrencyMint.swift
  Sources/Currency/CurrencyValue+Arithmetic.swift
  Sources/Currency/CurrencyValue+StringRepresentation.swift
  Sources/Currency/CurrencyValue.swift
  Sources/Currency/Documentation.docc/Articles/currency_mathematics.md
  Sources/Currency/Documentation.docc/Articles/custom_currencies.md
  Sources/Currency/Documentation.docc/Articles/displaying_currencies.md
  Sources/Currency/Documentation.docc/Articles/minting_currencies.md
  Sources/Currency/Documentation.docc/Currency.md
  Sources/Currency/Documentation.docc/Symbol Extensions/CurrencyMint.md
  Sources/Currency/Documentation.docc/Symbol Extensions/CurrencyValue.md
  Sources/Currency/MinorUnitRepresentation.swift
  Sources/ISOStandardCodegen/Codegen+CurrencyDefinitions.swift
  Tests/CurrencyTests/CurrencyMintTests.swift
  Tests/CurrencyTests/CurrencyValueTests.swift
Labels: documentation, enhancement, semver-patch

#50 Release 0.7.0 - Great Refactor
  .editorconfig
  .github/workflows/codecov.yml
  .github/workflows/tests.yml
  .gitignore
  ISO4217.csv
  ISO4217.json
  Package.swift
  Plugins/ISOStandardCodegenPlugin/plugin.swift
  README.md
  Sources/Currency/AnyCurrency+Algorithms.swift
  Sources/Currency/AnyCurrency.swift
  Sources/Currency/CurrencyDescriptor.swift
  Sources/Currency/CurrencyMint.swift
  Sources/Currency/CurrencyProtocol.swift
  Sources/Currency/CurrencyValue+Algorithms.swift
  Sources/Currency/CurrencyValue+Arithmetic.swift
  Sources/Currency/CurrencyValue+StringRepresentation.swift
  Sources/Currency/CurrencyValue.swift
  Sources/Currency/Documentation.docc/Articles/currency_mathematics.md
  Sources/Currency/Documentation.docc/Articles/custom_currencies.md
  Sources/Currency/Documentation.docc/Articles/displaying_currencies.md
  Sources/Currency/Documentation.docc/Articles/minting_currencies.md
  Sources/Currency/Documentation.docc/Currency.md
  Sources/Currency/Documentation.docc/Symbol Extensions/CurrencyMint.md
  Sources/Currency/Documentation.docc/Symbol Extensions/CurrencyValue.md
  Sources/Currency/Extensions/Decimal.swift
  Sources/Currency/Extensions/Sequence+Currency.swift
  Sources/Currency/MinorUnitRepresentation.swift
  Sources/ISOStandardCodegen/CSVParsing.swift
  Sources/ISOStandardCodegen/Codegen+CurrencyDefinitions.swift
  Sources/ISOStandardCodegen/Codegen+DefinitionParsing.swift
  Sources/ISOStandardCodegen/Codegen+FileHeader.swift
  Sources/ISOStandardCodegen/Codegen+MintLookup.swift
  Sources/ISOStandardCodegen/main.swift
  Tests/CurrencyTests/AnyCurrencyAlgorithmsTests.swift
  Tests/CurrencyTests/AnyCurrencyTests.swift
  Tests/CurrencyTests/CurrencyDescriptorTests.swift
  Tests/CurrencyTests/CurrencyMintTests.swift
  Tests/CurrencyTests/CurrencyValue+AlgorithmsTests.swift
  Tests/CurrencyTests/CurrencyValue+ArithmeticTests.swift
  Tests/CurrencyTests/CurrencyValue+StringRepresentationTests.swift
  Tests/CurrencyTests/CurrencyValueTests.swift
  Tests/CurrencyTests/Sequence+CurrencyTests.swift
Labels: semver-major

#52 Fix documentation links in README
  README.md
Labels: documentation

#51 Inject Locale on Localization tests
  Tests/CurrencyTests/CurrencyValue+StringRepresentationTests.swift
Labels: enhancement, semver-patch
